// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(EmailDbContext))]
    [Migration("20251123133636_Create")]
    partial class Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Priority");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#dc3545",
                            CreatedAt = new DateTime(2025, 11, 23, 13, 36, 33, 533, DateTimeKind.Utc).AddTicks(2035),
                            Description = "Urgent and critical emails requiring immediate attention",
                            DisplayName = "🔥 Most Important",
                            Name = "Most Important",
                            Priority = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#ffc107",
                            CreatedAt = new DateTime(2025, 11, 23, 13, 36, 33, 533, DateTimeKind.Utc).AddTicks(2039),
                            Description = "Important emails that need attention but are not urgent",
                            DisplayName = "⭐ Important",
                            Name = "Important",
                            Priority = 2
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#0d6efd",
                            CreatedAt = new DateTime(2025, 11, 23, 13, 36, 33, 533, DateTimeKind.Utc).AddTicks(2042),
                            Description = "Regular casual emails",
                            DisplayName = "🙂 Casual",
                            Name = "Casual",
                            Priority = 3
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#6c757d",
                            CreatedAt = new DateTime(2025, 11, 23, 13, 36, 33, 533, DateTimeKind.Utc).AddTicks(2044),
                            Description = "Promotional and marketing emails",
                            DisplayName = "🏷️ Promotional",
                            Name = "Promotional",
                            Priority = 4
                        });
                });

            modelBuilder.Entity("Models.Entities.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailProvider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExternalEmailId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReceivedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExternalEmailId")
                        .IsUnique()
                        .HasFilter("[ExternalEmailId] IS NOT NULL");

                    b.HasIndex("ReceivedTime");

                    b.HasIndex("SenderEmail");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Models.Entities.Email", b =>
                {
                    b.HasOne("Models.Entities.Category", "Category")
                        .WithMany("Emails")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Models.Entities.Category", b =>
                {
                    b.Navigation("Emails");
                });
#pragma warning restore 612, 618
        }
    }
}
